import { $ } from "bun"

/**
 * Compiles the distributable stylesheet and wraps it in a named cascade
 * layer. Layered rules lose to any unlayered rule, so a consuming app's
 * own Tailwind utilities (e.g. its "hidden md:flex" toggles) always win
 * over the identically-named utilities bundled here, while elements
 * rendered by this package remain fully styled.
 */
const OUTPUT_PATH = "src/styles.compiled.css"

const result =
  await $`tailwindcss -c tailwind.lib.config.js -i ./src/styles.lib.css --minify`.text()

const banner =
  "/* Generated by `bun run build:css` — do not edit. */\n@layer tscircuit-monaco-code-editor{"
await Bun.write(OUTPUT_PATH, `${banner}${result.trim()}}\n`)
console.log(`Wrote ${OUTPUT_PATH}`)
